#!/usr/bin/env node
/*
 * Regenerates the shared wire-format test vectors and compares them with the committed file.
 *
 * The JavaScript sender and the Java receiver each implement the BPlay wire format from scratch,
 * so nothing but a test stops them drifting apart. Both sides read tools/wire-vectors.txt: this
 * script checks the browser's encoder still produces those exact bytes, and WireVectorsTest checks
 * the Java decoder still understands them. A change to either implementation alone fails a build.
 *
 * Usage: node tools/wire-check.js [--write]
 */
'use strict';

const fs = require('fs');
const path = require('path');

const wire = require(path.join(__dirname, '..', 'firetv-receiver', 'src', 'main', 'assets',
  'web', 'wire.js'));

const VECTORS_FILE = path.join(__dirname, 'wire-vectors.txt');

function hex(bytes) {
  return Buffer.from(bytes).toString('hex');
}

/** Every vector is a case the two implementations have to agree on exactly. */
function buildVectors() {
  return {
    // A typical Android sender introducing itself.
    handshake_android: hex(wire.buildHandshake({
      pin: '4821',
      name: 'Pixel 7',
      platform: 'android',
      width: 1080,
      height: 2400,
      fps: 30,
      vcodec: 'video/avc',
      acodec: 'audio/mp4a-latm',
    })),

    // A browser with no PIN set and a device name needing no escaping.
    handshake_web_nopin: hex(wire.buildHandshake({
      pin: '',
      name: 'Windows PC (Chrome)',
      platform: 'web',
      width: 2560,
      height: 1440,
      fps: 30,
      vcodec: 'video/avc',
    })),

    // The separators the format has to escape, all in one value.
    handshake_escapes: hex(wire.buildHandshake({
      name: 'Bob=Home\nTV\\Backslash',
      platform: 'web',
    })),

    // A keyframe packet: header plus a short Annex-B payload.
    packet_keyframe: hex(wire.buildPacket(wire.TYPE.VIDEO, wire.FLAG_KEYFRAME, 1234567,
      new Uint8Array([0, 0, 0, 1, 0x67, 0x42, 0xe0, 0x1f, 0, 0, 0, 1, 0x68, 0xce,
        0, 0, 0, 1, 0x65, 0x88]))),

    // A timestamp past 2^32 microseconds, which is where a 32-bit field would wrap.
    packet_large_pts: hex(wire.buildPacket(wire.TYPE.VIDEO, 0, 9007199254,
      new Uint8Array([1, 2, 3, 4]))),

    // An empty payload, as sent by keep-alives.
    packet_ping: hex(wire.buildPacket(wire.TYPE.PING, 0, 0, new Uint8Array(0))),

    // The audio descriptor a browser sends in place of codec-specific data it does not have.
    params_audio_config: hex(wire.encodeParams({
      codec: 'opus',
      sampleRate: 48000,
      channels: 2,
    })),
  };
}

function serialise(vectors) {
  const header = '# Generated by tools/wire-check.js -- do not edit by hand.\n'
    + '# Shared conformance vectors for the BPlay wire format (JS sender <-> Java receiver).\n';
  return header + Object.keys(vectors).map((name) => name + ' ' + vectors[name]).join('\n') + '\n';
}

function main() {
  const generated = serialise(buildVectors());

  if (process.argv.includes('--write')) {
    fs.writeFileSync(VECTORS_FILE, generated);
    console.log('Wrote ' + VECTORS_FILE);
    return;
  }

  if (!fs.existsSync(VECTORS_FILE)) {
    console.error('Missing ' + VECTORS_FILE + '. Run: node tools/wire-check.js --write');
    process.exit(1);
  }

  const committed = fs.readFileSync(VECTORS_FILE, 'utf8');
  if (committed !== generated) {
    console.error('The browser encoder no longer produces the committed vectors.\n'
      + 'Either wire.js changed by accident, or the format changed on purpose -- in which case\n'
      + 'update the Java side too, then rerun with --write.');
    process.exit(1);
  }
  console.log('wire.js matches the committed vectors (' + Object.keys(buildVectors()).length
    + ' cases).');
}

main();
